version: '2'
services:
  cassandra:
    image: cassandra:2.2
    ports:
      - "9042:9042"

  s3:
    image: minio/minio
    command: /export
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
      - MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG

  talkpocketui:
    ports:
      - "3001:3001"
      - "3000:3000"
    build:
      context: "./ui"
      dockerfile: "Dockerfile"